### PR TITLE
waykiwaykiT

### PR DESCRIPTION
**Pull request by waykiwayki**
T shirt submission waykiwayki@hushmail.com

### CODE REVIEW

**Comment by waykiwayki** [comment]
It says uploads disabled.....see attached.

**Comment by waykiwayki** [comment]
Where can I upload?

see attached.

**Comment by LiteBit** [comment]
image
If you fork the repo you'll be able to upload on your copy of it and then create a pull request to merge the images in to the main repo

**Comment by waykiwayki** [comment]
Thank you.

Can you see the 3 jpg files  (designs) now:

https://github.com/waykiwayki/pops

**Comment by waykiwayki** [comment]
I still cannot see me in this list:

https://github.com/particlcommunity/pops/tree/master/pop-0002/projects

This is crazy, I worked in bespoke software for 10 years,  but this is all
very unclear how to simply upload some t-shirt designs.

**Comment by waykiwayki** [comment]
Can I not just upload the designs here please - see attached.

**Pull request merged**
